theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Brazilian Army Geographic Service Building Dataset
description: Dataset built by the Brazilian Army Geographic Service to train Deep Learning tasks.